apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-project
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres_demo
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
